name: Visual Smoke
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Serve static
        run: |
          npm i -g http-server
          nohup http-server -p 8080 . &
          sleep 2
      - name: Install Playwright
        run: |
          npm i -D playwright
          npx playwright install --with-deps chromium
      - name: Run smoke screenshots
        run: node scripts/smoke.js http://127.0.0.1:8080/index.html
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: smoke-screenshots
          path: screenshots-ci
